### ISSUE TITLE
Doctype html error on login

### ISSUE THREAD

**Issue by abboah** [hommym/Itirena-Backend#1]
![image](https://github.com/hommym/Itirena-Backend/assets/124472979/5f2e5ce0-bd8f-44ed-a3c5-1f5afa3962e1)

Error Code: on login...I/flutter ( 4437): Text("Error: FormatException: Unexpected character (at character 1)\n<!DOCTYPE html>\n^\n")

![Screenshot_1719844946](https://github.com/hommym/Itirena-Backend/assets/124472979/987ec7e1-dd51-4600-8ca3-22391926329c)

![image](https://github.com/hommym/Itirena-Backend/assets/124472979/66410453-75be-4d38-870c-66d4fa767cde)

**Comment by hommym** [comment]
change the username/email in the body of your request to either username or email, not both. so what you would do is write code to check if what the user has typed is a username or an email and based on that use either email or username in the body of the request and pass the necessary data.  Let me know if you would like to know how to do the check.

**Comment by abboah** [comment]
How would I do the check?

**Comment by hommym** [comment]
After you have retrieved the string typed in the text field in your code write an if statement to check for specific components that will make a string considered an email address. The two main components you should check  is " @" and ".com" (this should be the last component of the string) and if both of these are present the string is considered as an email  address otherwise the string is a username.  if you need a code sample let me know.
